### ISSUE TITLE
PI code checklist

### ISSUE THREAD

**Issue by aremazeilles** [nickkluft/udbenchmark_PIs#4]
FYI, the list of items I need to check for considering the code as eurobench-compatible:

- [ ] 1. Readme available (purpose, install, use, acknowledgment)
- [x] 2. identify test files (input --> output)
- [x] 3. confirm main program structure (input, output)
- [x] 4. check input-output file format
- [x] 5. insert docker generation files (TEC)
- [x] 6. insert CI process (TEC)
- [x] 7. insert docker hub secret (TEC)
- [x] 8. double check template spec again

We will do so progressively

**Comment by aremazeilles** [comment]
ping @nickkluft @alfonsotecnalia 
FYI:

* 4 is under process with @nickkluft 
* 5, 6 are in branches 

I think we should fix 4 before returning to 8.
But on the automation process (from our perspective), we are almost done.

**Comment by aremazeilles** [comment]
FYI @nickkluft , the docker image is now deployed onto docker hub: https://hub.docker.com/r/eurobenchtest/pi_udbenchmark/tags

That means that anyone can use your code (under linux), using the docker installation command described in the docker page, and then use the `docker run`, as described in your main Readme.
